cart/urls.py
from django.urls import path, include
from . import views

app_name = 'cart'

urlpatterns = [
    path('cart_detail', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),

]

get/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path, re_path
# from django.contrib.auth import views
from django.contrib.auth.views import LoginView, LogoutView,PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView, PasswordChangeDoneView, PasswordChangeView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tms.urls',namespace='tms')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    # url(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    # url(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
    # url(r'^accounts/login/$', views.login, name='login'),
    # url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),

    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(template_name='registration/logout.html'), LogoutView.next_page, name="logout"),
    re_path(r'^accounts/password/reset/$', PasswordResetView.as_view(template_name='registration/password_reset_page.html'), name='password_reset'),
    re_path(r'^accounts/password/reset/done/$', PasswordResetDoneView.as_view(template_name='registration/passwordreset_pagedone.html'), name='password_reset_done'),
    re_path( r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirmpage.html'), name='password_reset_confirm'),
    re_path(r'^accounts/password/reset/complete/$', PasswordResetCompleteView.as_view(template_name='registration/password_reset_completepage.html'), name='password_reset_complete'),
    re_path(r'^accounts/password/change/$', PasswordChangeView.as_view(template_name='registration/change-password.html'), name='password_change'),
    re_path(r'^accounts/password/change/done/$', PasswordChangeDoneView.as_view(template_name='registration/change-password-done.html'), name='password_change_done'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

tms/urls.py
from django.conf.urls import url
from . import views
from django.urls import path


app_name = 'tms'
urlpatterns = [
    path('', views.home, name='home'),
    url(r'^home/$', views.home, name='home'),
    path('register/', views.register, name='register'),

    path('product_list/', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('contact.html', views.contact, name='contact'),
]

tms/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tms:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tms:product_detail',
                       args=[self.id, self.slug])

tms/forms.py
from django import forms
from .models import Product
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password',
                                widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', max_length=254, help_text='Required. Enter a valid email address.')
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username','email', 'first_name','last_name','password1','password2')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

tms/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from cart.forms import CartAddProductForm
from django.views.generic import View
from django.http import HttpResponse
from django.shortcuts import redirect
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render


def home(request):
    return render(request, 'tms/home.html',
                  {'tms': home})


def register(request):
    print("entered into register view method")
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request,
                          'registration/registerdone.html',
                          {'form': form})
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", {"form": form})


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    print("categories: " + str(categories))
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,
                  'tms/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'tms/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def contact(request):
    if request.method == 'POST':
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']
        send_mail(
            message_name,
            message,
            message_email,
            ['jcui@unomaha.edu'],
            )

        return render(request,'tms/contact.html', {'message_name':message_name})
    else:
        return render(request, 'tms/contact.html', {})

tms/templates/tms/base.html
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8" />
   <title>{% block title %}Great Escapes Travel{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Great Escapes Travel</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="{% static 'css/tms.css' %}" rel="stylesheet">
</head>
<!-- <style>
  .navbar {
    margin-bottom: 0;
    border-radius: 0;
  }
  .row .col-md-6 .card {
    background: rgb(0, 0, 0);
    background: rgba(0, 0, 0, 0.1);
    color: black;
  }
</style>
<body>
 <nav class="navbar navbar-expand-sm bg-dark navbar-light mb-0"> -->

<style>
  body,html{
    height: 100%;
    margin: 0;
  }
  #events_card{
    margin: 0;
    padding-bottom: 40px;
  }
  .row .col-md-4 .card {
    background: rgb(0, 0, 0);
    background: rgba(0, 0, 0, 0.1);
    color: black;
  }
</style>
<body>
<!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">

  <a class="navbar-brand" href="/">
          <img src="{%static 'images/logo.jpg' %}" alt="Great Escapes Travel">
  </a> -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">

  <a href="/" class="navbar-brand">Great Escapes</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
          <!-- aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> -->
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><a class=nav-link href="/">Home</a></li>
      <li class="nav-item active"><a class=nav-link href="">Flights</a></li>
      <li class="nav-item active"><a class=nav-link href="">Hotels</a></li>
      <li class="nav-item active"><a class=nav-link href="">Rental Cars</a></li>
      <li class="nav-item active"><a class=nav-link href="{% url 'tms:product_list' %}">Shop</a></li>
      <li class="nav-item active"><a class=nav-link href="{% url 'tms:contact' %}">Contact Us</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'cart:cart_detail' %}" class="nav-link navbar-link-2 waves-effect" style="color:navajowhite ">
            <span class="badge badge-pill red" >1</span>
            <i class="glyphicon glyphicon-shopping-cart white" ></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
      </ul>
      {% else %}
      <form class="form-inline my-2 my-lg-0">
        <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
        <a href="{% url 'tms:register' %}" class="btn btn-primary ml-2">Sign Up</a>
      </form>
      {% endif %}
    </ul>
  </div>
</nav>
<div id="content container">
  {% block content %}
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/flight2.jpg' %}"  href="" class="d-block w-100" alt=""><a class=nav-link ></a>
        <div class="carousel-caption d-none d-md-block">
          <h5 style="color:black"><b>Book Flights</b></h5>
          <p style="color:black">Need a Break? Explore beautiful places just miles from home.</p>
        </div>
      </div>
      <div class="carousel-item">
      <img src="{% static 'images/hotel1.jpeg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:black">Book Hotels</h5>
        <p style="color:black">Enjoy your vacation in our best hotels.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/car1.jpg' %}" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:black">Book Rental cars</h5>
        <p style="color:black">Book your rental car and explore the city.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  {% endblock %}
</div>

</body>
</html>

tms/templates/tms/contact.html
{% load static %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Great Escapes Travel</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <link href="{% static 'css/tms.css' %}" rel="stylesheet">
<head>
    <meta charset="UTF-8">
    <title>Contact Page</title>
    <style>

</style>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark mb-4">
  <a href="/" class="navbar-brand">Great Escapes</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><a class=nav-link href="/">Home</a></li>
      <li class="nav-item active"><a class=nav-link href="">Flights</a></li>
      <li class="nav-item active"><a class=nav-link href="">Hotels</a></li>
      <li class="nav-item active"><a class=nav-link href="">Rental car</a></li>
      <li class="nav-item active"><a class=nav-link href="{% url 'tms:product_list' %}">Buy</a></li>
      <li class="nav-item active"><a class=nav-link href="{% url 'tms:contact' %}">Contact Us</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      {% if user.is_authenticated %}
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'cart:cart_detail' %}" class="nav-link navbar-link-2 waves-effect" style="color:navajowhite ">
            <span class="badge badge-pill red" >1</span>
            <i class="glyphicon glyphicon-shopping-cart white" ></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
          </div>
        </li>
      </ul>
      {% else %}
      <form class="form-inline my-2 my-lg-0">
        <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log In</a>
        <a href="{% url 'tms:register' %}" class="btn btn-primary ml-2">Sign Up</a>
      </form>
      {% endif %}
    </ul>
  </div>
</nav>
<div class="main">
    <div class="google-maps mb-10">
        {% if message_name %}
        <center>
            <h2>Thanks {{ message_name }}</h2>
            <p>We received your email and will respond shortly.</p>
        </center>
        <br/><br/><br/>
        {% else %}
        <div class="contact location">
            <h5>Address</h5>
            <p>6001 Dodge St, Omaha, NE 68182</p>
            <h5>Phone</h5>
            <p>+1.402.554.2800</p>
            <h5>Email</h5>
            <p>xxxx@unomaha.edu</p>
        </div>
        <div class="contact contact-form">
            <div class="section-heading">
                <div id="contact_title">Get In Touch </div>
                <div calss="line"></div>
            </div>

            <form method="post" action="{% url 'tms:contact' %}">
                {% csrf_token %}
                <div class="">
                    <input type="text" name="message-name" class="form-control1" placeholder="Your Name">
                </div>
                <div class="">
                    <input type="email" name="message-email" class="form-control1" placeholder="Your Email">
                </div>
	                <textarea name="message" class = "form-control2" placeholder="Your Message"></textarea>
                <div class="col-12">
                    <button type="submit" class="btn btn-primary ml-2">Send Message</button>
                </div>
            </form>
        </div>
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d23994.603449878538!2d-96.01945963001363!3d41.258249700000015!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x4dbea6a55857784f!2sUniversity%20of%20Nebraska%20Omaha!5e0!3m2!1sen!2sus!4v1595909007554!5m2!1sen!2sus" width="1200" height="450" frameborder="0" style="text-align: cente; border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe></div>

</div>
    {% endif %}
</div>
</body>

tms/templates/tms/detail.html
{% extends "tms/base.html" %}
{% load static %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
<div class="row wow fadeIn">
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %} {% static 'img/no_image.png' %}{% endif %}">
    <div class="">
      <h1>{{ product.name }}</h1>
      <h2><strong>Category:</strong>
        <a href="{{ product.category.get_absolute_url }}">
          {{ product.category }}
        </a>
      </h2>
      <p class="price"><strong> Price :</strong> ${{ product.price }}</p>
    </div>
    <form action="{% url 'cart:cart_add' product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
    <!--{{ product.description|linebreaks }}-->
  </div>
</div>
{% endblock %}

tms/templates/tms/home.html
{% extends 'tms/base.html' %}
{% load static %}
{% block content %}
 <div id="content container">
    <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        <img src="{% static 'images/flight2.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:black"><b>Book Flights</b></h5>
        <p style="color:black">Need a Break? Explore beautiful places just miles from home.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/hotel1.jpeg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:black">Book Hotels</h5>
        <p style="color:black">Enjoy your vacation in our best hotels.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/car1.jpg' %}" class="d-block w-100" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h5 style="color:black">Book Rental Cars</h5>
        <p style="color:black">Book your rental car and explore the city.</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
 </div>
{% endblock %}

tms/templates/tms/list.html
{% extends "tms/base.html" %}
{% load static %}
{% block title %}
  {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<style>
        body,html{
            height: 100%;
            margin: 0;
            background: #ffffff;
        }
        #events_card{
            padding-left:10px;
            padding-right:40px;
            padding-bottom: 40px;
        }
</style>

  <div id="sidebar">
    <h3>Categories</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'tms:product_list' %}">All</a>
      </li>
      {% for c in categories %}
        <li {% if category.slug == c.slug %}class="selected"
        {% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
<main class="mt-2 pt-2">
  <div class="container dark-grey-text mt-3" align="center">
    <div id="main" class="product-list">
      <!--Grid row-->
      <div class="row wow fadeIn">
        <!--Grid column-->
        <div class="col-md-10 mb-6">
        <h1>{% if category %}{{ category.name }}{% else %}Products {% endif %}</h1>
        {% for product in products %}
        <div class="item">
          {% if user.is_authenticated %}
          <a href="{{ product.get_absolute_url }}">
             {%  else  %}
            <a href = "{% url 'login' %}">
          {% endif %}
            <img width = 150px height = 200px align = center src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
          <br>
          ${{ product.price }}
        </div>
        {% endfor %}
      </div>
    </div>
  </div> <!--Grid column-->
  </div> <!--Grid row-->

</main>
{% endblock %}